server:
  port: 8081 # 端口

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/cms?serverTimezone=Asia/Shanghai
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 1000ms
    port: 6379

  server:
    port: 8080
  thread:
    size: 6

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
#  mapper-locations: classpath:org/lqh/home/mapper/xml/*.xml



---
spring:
  profiles: test
  jackson:
    date-format: 年-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8082
---
spring:
  profiles: prd
  jackson:
    date-format: yyyy-月-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8083



